### PR TITLE
feat: add header-related methods to Response

### LINKED ISSUE #149: add `get_all` to `Headers`
The current implementation only returns the first key found:

https://github.com/http-rs/surf/blob/0cf721dacd01b5dfa94623906a0353f92449f29c/src/headers.rs#L18-L23

### PR DESCRIPTION
**Pull request by SirWindfield**
This PR adds various methods for working with the received headers from a response object.
An iterator over the names of each header field has been added in PR #171.

Closes #149.

### CODE REVIEW

**Comment by Fishrock123** [comment]
This functionality has been merged via https://github.com/http-rs/surf/pull/191

**Comment by SirWindfield** [comment]
Thanks for letting me know @Fishrock123. Any particular reason why you decided to create another PR instead of merging the two that were already present? :smile:

**Comment by Fishrock123** [comment]
Sorry, there was a lot to get in sync with Tide's api, and it was easier to do the changes combined.

**Comment by SirWindfield** [comment]
No need to apologize! Thanks for letting me know :) Would be awesome if someone could take a look at https://github.com/http-rs/surf/pull/190, it's super short :)

Thanks for creating the #191 though :)

**Pull request closed without merging**
