### PR TITLE
Makes http_client contents public.

### LINKED ISSUE #54: What's the type of `surf::Client::new()` ?
Hello, I'm trying to create a client instance and pass it to functions for reuse:
```
let client = surf::Client::new();
get_item(client, url);
```

But what type should I use for the function parameter ?
```
async fn get_item(client: ???, url: String) -> ...
```

### PR DESCRIPTION
**Pull request by IslandUsurper**
## Description

However, to retain stability guarantees, their implementations are kept private to the crate.

## Motivation and Context
Fixes #54.

`Client` and `Request` are hard to pass around to functions because of their type parameter. Every user of _surf_ has to make these functions generic over the chosen HTTP client, even though only one should ever be used at a time. By exposing the names of the HTTP clients, _surf_ users can use the specific type instead of a trait-bound parameter.

## How Has This Been Tested?

`cargo +nightly test` passed on Linux x64. I am unsure how to get the hyper-client and wasm-client features to pass tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

`IsahcClient` is no longer `Default`, but this didn't seem to be used anyway.

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
The build errored. I've gone ahead and restarted it. -- we should merge this if it passes and cut a new minor release.

**Comment by IslandUsurper** [comment]
The build timed out either during or after creating the sccache directory. When I ran the commands on my own computer, I discovered warnings for missing documentation, so I added some. Hopefully, Travis will work correctly for this new commit.

**Comment by pimeys** [comment]
Would it be possible to not make the types public, but instead use dynamic dispatch in the `Client`? It would not be that big of an issue performance-wise, but would allow us to not have a type parameter in `Client` at all...

**Comment by pimeys** [comment]
Wrote another issue about my suggestion https://github.com/rustasync/surf/issues/69

**Comment by IslandUsurper** [comment]
Since #70 fixed the Travis cache, can we retry this build?

**Comment by yoshuawuyts** [comment]
We've published https://github.com/http-rs/http-client today which makes this public. We should move Surf over to use it :sparkles:

**Pull request closed without merging**
