### PR TITLE
Move to http-client crate

### PR DESCRIPTION
**Pull request by pwoolcoc**
This PR removes the `http-client` module and uses the new `http-client` crate instead

### CODE REVIEW

**Comment by pwoolcoc** [comment]
It is currently using my branch from this PR: https://github.com/http-rs/http-client/pull/7 . I wanted to open this now to get comments on it, but we'll need a new `http-client` published with the futures 0.3.1 changes before this can be merged

**Comment by pwoolcoc** [comment]
#122 will have to be merged in order for this to pass

**Comment by mmstick** [comment]
This finally made surf usable in the [async-fetcher crate I've developed for Pop!\_OS](https://github.com/pop-os/async-fetcher).

**Comment by yoshuawuyts** [comment]
@pwoolcoc https://github.com/http-rs/surf/pull/122 was merged; I'd love to see us make progress on this patch and I believe it's unblocked now. Thanks so much for the work you've put in!

**Comment by pwoolcoc** [comment]
@yoshuawuyts I'd love to, we need a new `http-client` crate published first though. The existing version of `http-client` used futures 0.3.0-alpha, so I had to upgrade it to 0.3.1 here: https://github.com/http-rs/http-client/pull/7

Right now the only thing blocking this patch is that it is depending on the master branch of `http-client` in order to compile

**Comment by yoshuawuyts** [comment]
@pwoolcoc thanks for pointing me to the PR. Apparently I wasn't watching `http-client` so I've missed some of the activity there. Digging in now!

**Comment by yoshuawuyts** [comment]
@pwoolcoc published `http-client@1.1.0` which should unblock this patch!

**Pull request merged**
